package com.latchpoint.auth.service;
import com.latchpoint.auth.config.AppProperties; import com.latchpoint.auth.dto.Responses.LoginResponse; import com.latchpoint.auth.exception.AuthExceptions.*; import com.latchpoint.auth.model.*; import com.latchpoint.auth.repository.*; import jakarta.servlet.http.HttpServletRequest; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant;
@Service public class AuthenticationService { private final UserRepository users; private final PasswordEncoder encoder; private final SessionService sessions; private final MfaService mfa; private final EventLogService events; private final AppProperties props; private final MfaChallengeRepository challenges;
 public AuthenticationService(UserRepository u,PasswordEncoder e,SessionService s,MfaService m,EventLogService ev,AppProperties p,MfaChallengeRepository c){users=u;encoder=e;sessions=s;mfa=m;events=ev;props=p;challenges=c;}
 @Transactional public LoginResponse login(String username,String password,HttpServletRequest req){User u=users.findByUsername(username).orElse(null); if(u!=null&&u.getLockedUntil()!=null&&u.getLockedUntil().isAfter(Instant.now())){events.record("LOGIN_FAILED","failed",username,req);throw new TooManyAttempts();}
  if(u==null||!u.isEnabled()||!encoder.matches(password,u.getPasswordHash())){if(u!=null){u.setFailedLoginAttempts(u.getFailedLoginAttempts()+1);if(u.getFailedLoginAttempts()>=props.getRateLimit().getMaxFailures())u.setLockedUntil(Instant.now().plusSeconds(props.getRateLimit().getBlockMinutes()*60));users.save(u);}events.record("LOGIN_FAILED","failed",username,req);throw new InvalidCredentials();}
  u.setFailedLoginAttempts(0);u.setLockedUntil(null);users.save(u);events.record("LOGIN_SUCCESS","success",username,req); if(u.isMfaEnabled()){return LoginResponse.mfa(mfa.createChallenge(u));}String token=sessions.createSession(u); return LoginResponse.session(token, java.time.Instant.now().plusSeconds(Math.min(props.getSession().getTimeoutMinutes(),props.getJwt().getExpiryMinutes())*60).toString());
 }
 @Transactional public LoginResponse verifyMfa(String id,String code){mfa.verify(id,code); var c=challenges.findByChallengeId(id).orElseThrow(InvalidMfa::new); String token=sessions.createSession(c.getUser()); return LoginResponse.session(token, Instant.now().plusSeconds(Math.min(props.getSession().getTimeoutMinutes(),props.getJwt().getExpiryMinutes())*60).toString());}
}
