package com.latchpoint.auth.service;
import com.latchpoint.auth.config.AppProperties; import com.latchpoint.auth.dto.Responses.*; import com.latchpoint.auth.exception.AuthExceptions.InvalidConfiguration; import com.latchpoint.auth.model.FrameworkConfiguration; import com.latchpoint.auth.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class ManagementService { private final ConfigurationRepository configs; private final AuthEventRepository events; private final AppProperties props;
 public ManagementService(ConfigurationRepository c,AuthEventRepository e,AppProperties p){configs=c;events=e;props=p;}
 private FrameworkConfiguration config(){return configs.findById(1L).orElseGet(()->configs.save(new FrameworkConfiguration()));}
 public DashboardResponse dashboard(){Instant from=Instant.now().minus(24,java.time.temporal.ChronoUnit.HOURS), now=Instant.now(); long success=events.countByEventTypeAndTimestampBetween("LOGIN_SUCCESS",from,now), failed=events.countByEventTypeAndTimestampBetween("LOGIN_FAILED",from,now); var c=config(); return new DashboardResponse(failed>20?"at_risk":"secure",new RecentLogins(success,failed),c.isMfaEnabled(),props.getAdapterEndpoint()==null||props.getAdapterEndpoint().isBlank()?"disconnected":"connected");}
 public EventsResponse eventList(String status,Instant from,Instant to){if(from==null)from=Instant.now().minus(30,java.time.temporal.ChronoUnit.DAYS);if(to==null)to=Instant.now();var list=status==null?events.findByTimestampBetweenOrderByTimestampDesc(from,to):events.findByStatusAndTimestampBetweenOrderByTimestampDesc(status,from,to);return new EventsResponse(list.stream().map(e->new EventResponse(String.valueOf(e.getId()),e.getTimestamp().toString(),e.getUsername(),e.getStatus(),e.getIpAddress())).toList());}
 public ConfigResponse getConfig(){var c=config();return toResponse(c);}
 @Transactional public ConfigResponse update(ConfigRequest r){if(r.passwordPolicy()==null||r.passwordPolicy().minLength()<8||r.passwordPolicy().minLength()>128||r.passwordPolicy().expiryDays()<1||r.passwordPolicy().expiryDays()>3650||r.sessionTimeoutMinutes()<1||r.sessionTimeoutMinutes()>1440)throw new InvalidConfiguration("invalid_configuration");var c=config();c.setMfaEnabled(r.mfaEnabled());c.setMinLength(r.passwordPolicy().minLength());c.setRequireSymbol(r.passwordPolicy().requireSymbol());c.setExpiryDays(r.passwordPolicy().expiryDays());c.setSessionTimeoutMinutes(r.sessionTimeoutMinutes());configs.save(c);return toResponse(c);}
 private ConfigResponse toResponse(FrameworkConfiguration c){return new ConfigResponse(c.isMfaEnabled(),new PasswordPolicy(c.getMinLength(),c.isRequireSymbol(),c.getExpiryDays()),c.getSessionTimeoutMinutes(),new AdapterConnection(props.getAdapterEndpoint(),props.getAdapterEndpoint()==null||props.getAdapterEndpoint().isBlank()?"disconnected":"connected"));}
 public AlertsResponse alerts(){Instant now=Instant.now(), since=now.minus(15,java.time.temporal.ChronoUnit.MINUTES);List<AlertResponse> out=new ArrayList<>(); long failures=events.countByEventTypeAndTimestampAfter("LOGIN_FAILED",since); if(failures>=5)out.add(new AlertResponse("failed-login-spike","failed_login_spike","Multiple failed login attempts detected in the last 15 minutes.",now.toString())); return new AlertsResponse(out);}
}
